image aoh_appears:
    "cgs/2AOH.png" with Dissolve(.1)
    pause(0.06)
    "cgs/3AOH.png" with Dissolve(.1)
    pause(0.07)
    "cgs/4AOH.png" with Dissolve(.1)
    pause(0.08)
    "cgs/5AOH.png" with Dissolve(.1)
    pause(0.09)
    "cgs/6AOH.png" with Dissolve(.1)
    pause(0.1)
    "cgs/7AOH.png" with Dissolve(.1)
    pause(0.11)
    "cgs/8AOH.png" with Dissolve(.1)
